// Generated by CoffeeScript 1.3.3
(function() {

  window.VIMEditorDefaults = {
    cursorColor: 'black',
    cursorWidth: 9,
    cursorHeight: 18,
    cursorLeft: 0,
    cursorTop: 0
  };

  window.VIMEditorActions = {
    keypressHandler: function(e) {
      var content, keyCodeStr;
      e = e || window.event;
      console.log(e.keyCode);
      keyCodeStr = String.fromCharCode(e.keyCode);
      switch (keyCodeStr) {
        case "k":
          return (function() {
            var cursorTopMargin;
            VIMEditorDefaults.cursorTop -= VIMEditorDefaults.cursorTop === 0 ? 0 : 1;
            cursorTopMargin = VIMEditorDefaults.cursorTop * VIMEditorDefaults.cursorHeight;
            return $('#cursor').css('marginTop', cursorTopMargin);
          })();
        case "j":
          return (function() {
            var cursorTopMargin;
            VIMEditorDefaults.cursorTop += 1;
            cursorTopMargin = VIMEditorDefaults.cursorTop * VIMEditorDefaults.cursorHeight;
            return $('#cursor').css('marginTop', cursorTopMargin);
          })();
        case "l":
          return (function() {
            var cursorLeftMargin;
            VIMEditorDefaults.cursorLeft += 1;
            cursorLeftMargin = VIMEditorDefaults.cursorLeft * VIMEditorDefaults.cursorWidth;
            return $('#cursor').css('marginLeft', cursorLeftMargin);
          })();
        case "h":
          return (function() {
            var cursorLeftMargin;
            VIMEditorDefaults.cursorLeft -= VIMEditorDefaults.cursorLeft === 0 ? 0 : 1;
            cursorLeftMargin = VIMEditorDefaults.cursorLeft * VIMEditorDefaults.cursorWidth;
            return $('#cursor').css('marginLeft', cursorLeftMargin);
          })();
        case "x":
          return (function() {
            var content;
            content = $('#vimEditor-content').html();
            content = content.split('');
            content.splice((VIMEditorDefaults.cursorLeft === 0 ? 0 : VIMEditorDefaults.cursorLeft - 1), 1);
            return $('#vimEditor-content').html(content.join(''));
          })();
        case "esc":
          return (function() {
            return console.log('ESC');
          })();
        case "i":
        case "":
          return (function() {
            VIMEditor.mode = 'insert';
            return $('#cursor').width('2px');
          })();
        default:
          content = $('#vimEditor-content').html();
          content = content.split('');
          content.splice(VIMEditorDefaults.cursorLeft - 1, 0, keyCodeStr);
          return $('#vimEditor-content').html(content.join(''));
      }
    }
  };

  window.VIMEditor = {
    init: (function() {
      setInterval((function() {
        return $('#cursor').toggle();
      }), 500);
      return $(document).on('keypress', VIMEditorActions.keypressHandler);
    }),
    mode: 'normal'
  };

  jQuery(function() {
    return VIMEditor.init();
  });

}).call(this);
